### ISSUE TITLE
Still having : throw new Error('Cyclic dependency: '+JSON.stringify(node))

### ISSUE THREAD

**Issue by darkylmnx** [marcelklehr/toposort#25] opened 2018-06-16 05:28 UTC
I just upgraded to the new Vue CLI which internally uses new Webpack 4 which uses toposort, as soon as I upgraded, this happend.

![image](https://user-images.githubusercontent.com/1426357/41496054-6d9a6eca-7136-11e8-8416-e1006976c9c6.png)

**Comment by marcelklehr** [comment] 2018-06-16 15:00
Hey :)

Are you reporting this to this repo because of the "circular structure" JSON.stringify error? If not, then this looks like a normal error due to wrong use of toposort. Toposort throws an error if you try to sort circular data.

**Comment by darkylmnx** [comment] 2018-06-16 18:01
@marcelklehr yes i'm talking about the ""circular structure" JSON.stringify error". I'm not the one using toposort here, it seems to be a dep of webpack 4 and when the dep is >= 1.0.7 I have this error, when I force toposort to 1.0.6 or under it works

**Comment by darkylmnx** [comment] 2018-06-16 18:02
```
toposort@^1.0.0:
  version "1.0.6"
  resolved "https://registry.yarnpkg.com/toposort/-/toposort-1.0.6.tgz#c31748e55d210effc00fdcdc7d6e68d7d7bb9cec"
```

this works without an error, but any time I upgrade something I get this lock with the error mentioned in the console
```
toposort@^1.0.0:
  version "1.0.7"
  resolved "https://registry.yarnpkg.com/toposort/-/toposort-1.0.7.tgz#c31748e55d210effc00fdcdc7d6e68d7d7bb9cec"
```

**Comment by marcelklehr** [comment] 2018-06-16 18:20
> when I force toposort to 1.0.6 or under it works

oh. Interesting!

**Comment by marcelklehr** [comment] 2018-06-16 18:31
However, the exact error you describe *cannot* happen with v1.0.7 anymore, because line 21 has been changed https://github.com/marcelklehr/toposort/compare/v1.0.4...v1.0.7

This diff also shows the difference between version 1.0.4 and v1.0.7 which is one test and said change around line 21. I highly doubt that there's an input that throws an error in v1.0.7 but doesn't in v1.0.4, but if you like you can create a gist or a repo that I can use to reproduce and debug.

**Comment by darkylmnx** [comment] 2018-06-16 18:36
I'll try to get the bug on a repo, but I think if the problem is a cyclic
dependency it should output the files concerned, whereas, here it doesn't
so it's quite hard to figure out what's wrong.

More again since it's a dep used by webpack and not directly my project.

Le sam. 16 juin 2018 à 20:31, Marcel Klehr <notifications@github.com> a
écrit :

**Comment by alkurbatov** [comment] 2018-08-06 07:57
Good morning, everybody.
I've got the same issue with toposort recently. While the real problem was in my Vue code (circular dependency in one of the components) toposort failed with "circular structure" in JSON.stringify.
It is turned out that when toposort investigates the circular dependency error it tries to throw out a Error and notify about it, however, it also tries to use JSON.stringify on the incoming json structure.
In my case the json structure was circular too so toposort failed to throw Error and hid the original reason.

This happened on 1.0.4 and 1.0.6.

Hope this helps.

**Comment by marcelklehr** [comment] 2018-08-06 14:07
Hey Alexander,
I encourage you to try v1.0.7 which was released in April mitigate this problem ;)

**Comment by alkurbatov** [comment] 2018-08-06 14:24
Hey @marcelklehr ,
thank you for the suggestion, the error processing code is much better now. I will update the dependency :)

**Closed as completed** 2019-02-14 17:44 UTC
